# Generated by Django 4.1.3 on 2022-12-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=150)),
                ('production_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('body_style', models.CharField(choices=[('Suv', 'Suv'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('Wagon', 'Wagon'), ('Passenger Van', 'Passenger Van'), ('Pickup truck', 'Pickup Truck'), ('Convertible', 'Convertible')], max_length=15)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('ORANGE', 'Orange'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('INDIGO', 'Indigo'), ('PURPLE', 'Purple'), ('WHITE', 'White'), ('BLACK', 'Black'), ('GRAY', 'Gray')], max_length=6)),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=8)),
            ],
        ),
    ]
