# Generated by Django 4.1.3 on 2022-12-20 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=500)),
                ('make', models.CharField(choices=[('Ferrari', 'Ferrari'), ('BMW', 'Bmw'), ('Mercedes', 'Mercedes'), ('Lamborghini', 'Lamborghini'), ('Porsche', 'Porsche'), ('Audi', 'Audi'), ('Tesla', 'Tesla'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia')], max_length=30)),
                ('url', models.CharField(max_length=150)),
                ('production_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('body_style', models.CharField(choices=[('Suv', 'Suv'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('Wagon', 'Wagon'), ('Passenger Van', 'Passenger Van'), ('Pickup truck', 'Pickup Truck'), ('Convertible', 'Convertible')], max_length=15)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Indigo', 'Indigo'), ('Purple', 'Purple'), ('White', 'White'), ('Black', 'Black'), ('Gray', 'Gray')], max_length=6)),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=8)),
                ('favourites', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
